spring:
  profiles:
    active: native
  application:
     name: config-service
  cloud:
    config:
      client:
        native:
          search-locations: classpath:/configurations

server:
  port: 8888
